### ISSUE TITLE
Cant't import from "@framer/lintonye.parallax/code" in framer web

### ISSUE THREAD

**Issue by ShinichiroMike** [lintonye/useParallax#1]
I'm trying to write overrides on framer web, and I get problems on this line:

import { useSticky, useScroll } from "@framer/lintonye.parallax/code"

I get this error message: "code_1.useScroll is not a function." 
And I'm unable to use it.
The layouts work perfectly without coding.

There is any solution to importing this module?

**Comment by lintonye** [comment]
This is a bug in Framer's editor. It's a false positive which can be ignored this way:

```ts
// @ts-ignore
import { useSticky, useScroll } from "@framer/lintonye.parallax/code"
```

Check out the [Demo project](https://framer.com/projects/new?duplicate=kdJQdrPzI7O29AFdyoem) on Framer Web.

**Comment by devinhalladay** [comment]
I'm having this issue as well...

```js
// @ts-ignore
import { useSticky, useScroll } from "@framer/lintonye.parallax/code"
```

Throws the same error from OP above.

Here's a link to my prototype: https://framer.com/share/gnPeO7aOVjTeZYWYlEth/LO6lB0Ln4

EDIT: I am using the code — verbatim — from your example project's sticky header example.

**Comment by lintonye** [comment]
@devinhalladay Have you tried the demo project above? In fact even with that error, the project should work.

**Comment by devinhalladay** [comment]
@lintonye yep, the demo project works just fine. That's why I'm so confused about this error. When I have time, I'll try replicating my current prototype within a copy of your demo project, and post an update here on whether or not that resolves the issue.

**Comment by davidrittri** [comment]
The issue still exists. When I play around in the demo project everything works. If I copy the "Vertical" example frames, as well as create an override in my file, that is verbatim a copy paste of the relevant override file it will not work and just tell me 
"Error in ParallaxScroll.tsx"
"code_1.useScroll is not a function"
17 errors in the console, most of them look similar to this
![image](https://user-images.githubusercontent.com/73342103/119816149-a8e3e900-beec-11eb-9a6d-63f2c5b65349.png)

**Comment by devinhalladay** [comment]
I think this must be related to a chance in the way Framer handles code components: https://www.framer.com/support/using-framer/legacy-code/
